initial commit
Frix-x/klippain pull request #166
Opened 2023-04-27 18:28 UTC by Surion79

2023-04-27 18:29 UTC, Surion79 commented
Ok, VS Code created an automated PR with commit note. nice... Anyway, after messing up my first PR, here is the one

2023-04-30 21:47 UTC, Frix-x requested changes
So I have done a first pass on the PR.
This looks promising but there is multiple files without the newline at the end of the file (I think I will try to find a way to enforce it automatically using commit hooks).

Also it look like it's not finished as there is nothing in the printer.cfg at the moment.

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/XY/default_wiring.cfg
> +endstop_pin: Y_STOP
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/Z/TriZero_tmc2209.cfg
> +[include ../tmc/z_tmc2209_1M.cfg]
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/Z/Trident_tmc2209.cfg
> +[include ../tmc/z_tmc2209_3M.cfg]
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/Z/V0_tmc2209.cfg
> +[include ../tmc/z_tmc2209_1M.cfg]
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/Z/V2.4_tmc2209.cfg
> +[include ../tmc/z_tmc2209_4M.cfg]
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/Z/default_wiring_1M.cfg
> +endstop_pin: Z_STOP
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/Z/default_wiring_3M.cfg
> +enable_pin: !Z2_ENABLE
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/Z/default_wiring_4M.cfg
> +enable_pin: !Z3_ENABLE
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/tmc/x_tmc2209.cfg
> +stealthchop_threshold: 0
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/tmc/y_tmc2209.cfg
> +stealthchop_threshold: 0
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/tmc/y_tmc2209_V0specific.cfg
> +driver_PWM_REG: 4
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/tmc/z_tmc2209_1M.cfg
> +stealthchop_threshold: 0
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/tmc/z_tmc2209_3M.cfg
> +stealthchop_threshold: 0
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/axis/tmc/z_tmc2209_4M.cfg
> +stealthchop_threshold: 0
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/extruder/default_wiring.cfg
> +sensor_pin: E_TEMPERATURE
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/extruder/tmc/e_tmc2209.cfg
> +stealthchop_threshold: 0
Can you add a newline at the end of the file?

2023-04-30 21:47 UTC, Frix-x commented on config/hardware/extruder/tmc/e_tmc2240.cfg
> +stealthchop_threshold: 0
Can you add a newline at the end of the file?

2023-05-01 07:00 UTC, Surion79 commented
Yeah, unfortunately i scrapped by accident my initial PR. Printer.cfg was already prepped

2023-05-03 07:42 UTC, merged

2023-05-03 07:43 UTC, Frix-x commented
I merged the PR into a branch in my repo to be able to work on it correctly