Add support for sensorless homing on CoreXZ & Cartesian
Frix-x/klippain pull request #273
Opened 2023-08-06 09:13 UTC by ndanyluk

Hi Frix!

New PR here to tweak the homing override such that CoreXZ behaves a little better with sensorless homing.  I've tested this PR on my VSW and it appears to be working nicely.

Specifically, I added a new variable to track kinematic type, then I use that variable in homing_override.cfg to control which motors have their current reduced during homing (no change for corexy).  Additionally, I increased the 1s wait to 2s between homing moves to allow stallguard registers to clear.  CoreXZ also required a 2s wait after the initial Z hop for the same reason.

Let me know if you need any changes or additional testing and I'd be happy to do it!

2023-08-07 07:20 UTC, Frix-x commented
Hey thanks for this PR!

I'll take some time to review it today at the end of the day :)

2023-08-07 14:09 UTC, Frix-x requested changes
Ok I've took some time to have a look. It's pretty good already but to make it a little bit more clean, I think you can use directly the Klipper configured kinematics instead of adding a new variable. What do you think about it?

Something like this should do the trick:
```
{% set kinematics = printer["configfile"].config["printer"]["kinematics"] %}
```

2023-08-08 04:29 UTC, ndanyluk commented
> Ok I've took some time to have a look. It's pretty good already but to make it a little bit more clean, I think you can use directly the Klipper configured kinematics instead of adding a new variable. What do you think about it?
> 
> Something like this should do the trick:
> 
> ```
> {% set kinematics = printer["configfile"].config["printer"]["kinematics"] %}
> ```

this is great I didn't realize I could do this! I'll implement and update the PR :)

2023-08-08 04:56 UTC, ndanyluk commented
@Frix-x ok that seems to work! Tested on my VSW with the suggested change and it still homes successfully/appears to set the currents properly for XZ, then Y

2023-08-08 05:16 UTC, ndanyluk commented
Ok I think I fixed it and squashed the commit history properly

2023-08-08 08:45 UTC, Frix-x commented
Thank you very much for this, it's a pretty cool feature :)

2023-08-08 08:45 UTC, Frix-x approved these changes

2023-08-08 08:46 UTC, merged