Created bypass checks for MMU
Frix-x/klippain pull request #321
Opened 2023-10-23 12:54 UTC by smwoodward

2023-10-23 18:48 UTC, Benoitone requested changes
Thanks and can you check this changes?

2023-10-23 18:48 UTC, Benoitone commented on macros/base/start_print.cfg
> +                    {% if printer.mmu.tool|int != INITIAL_TOOL and INITIAL_TOOL != -2 %}
```suggestion
                    {% if printer.mmu.tool|int != INITIAL_TOOL %}
```

2023-10-23 18:48 UTC, Benoitone commented on macros/base/start_print.cfg
> +                    {% if printer.mmu.tool|int != INITIAL_TOOL  and INITIAL_TOOL != -2 %}
```suggestion
                    {% if printer.mmu.tool|int != INITIAL_TOOL %}
```

2023-10-23 18:48 UTC, Benoitone commented on macros/base/start_print.cfg
> +            {% endif %}
```suggestion
            {% endif %}
```

2023-10-23 18:48 UTC, Benoitone commented on macros/base/start_print.cfg
> +            {% if INITIAL_TOOL != -2 %}
```suggestion
           {% if INITIAL_TOOL != -2 or printer.mmu.tool|int != -2 %}
```

2023-10-23 22:33 UTC, Benoitone commented
But maybe with only
{% if printer.mmu.enabled and printer.mmu.tool|int != -2 %}
in the differents macros is enough

2023-10-24 12:03 UTC, smwoodward commented
That looks good to me.  I'm not a developer by trade so I know there are always better ways to handle things.

2023-10-24 12:45 UTC, Benoitone commented
> That looks good to me.  I'm not a developer by trade so I know there are always better ways to handle things.

I'm not developer too 😀
Based on your work I push a new branch for testing a simplified things.
Can you have a look on it?
https://github.com/Frix-x/klippain/tree/Happy_Hare_Benoit

2023-10-26 14:48 UTC, closed without merging