add config files for micron+ (180mm) printer
Frix-x/klippain pull request #335
Opened 2023-11-08 16:09 UTC by Fragmon

2023-11-08 21:35 UTC, Frix-x requested changes
Hello,

Thank you for this PR. I'll just need some small changes to clean it a little bit and I'll merge it :)

2023-11-08 21:35 UTC, Frix-x commented on config/software/tilting/qgl_180mm.cfg
> +   170,30
Same question about the points here: 180 seems high for a 180mm bed. Is this right?

2023-11-10 16:11 UTC, Fragmon commented
I change the values and delete the #micron+

2023-11-10 16:30 UTC, Frix-x approved these changes
Super! Thanks for this, I'll merge it!

2023-11-10 16:30 UTC, merged