added templates for BTT MMB board
Frix-x/klippain pull request #354
Opened 2023-11-21 17:21 UTC by Surion79

New template for new BTT MMB CAN v1.0

Link:
https://github.com/bigtreetech/MMB

Important, not all pins are shown on the JPG
https://github.com/bigtreetech/MMB/blob/master/Hardware/MMB%20CAN%20V1.0-Pin.jpg?raw=true

I extracted the missing diag pins from the referenced sample config files from the linked repo.

CS and UART are the same pins based on the schematic and the sample config.

2023-11-22 08:17 UTC, Frix-x requested changes

2023-11-22 08:17 UTC, Frix-x commented on user_templates/mcu_defaults/ercf/BTT_MMB_CAN_v1.0.cfg
> +# If you want to override the wiring of the Fystec ERCF ERB, keep in mind that this
Please change the name of the board here to the correct name (probably a copy/paste typo)

2023-11-23 07:08 UTC, Frix-x approved these changes

2023-11-23 07:09 UTC, Frix-x commented
Since this new template doesn't have any impact beside adding a template, I'll merge to main directly to make it available for everyone now.

2023-11-23 07:09 UTC, merged

2023-11-29 08:28 UTC, Benoitone commented
@Surion79 Hello, do you use this card with the ERCF? I had already implemented it in the branch for HH v2 (HAPPY_HARE_BENOIT for HHv2.2) and they are in conflict...