Add BTT Kraken
Frix-x/klippain pull request #476
Opened 2024-02-14 17:28 UTC by Benoitone

Add BTT Kraken Board template to Klippain

2024-02-14 21:32 UTC, Surion79 commented
please wait until Frix has released a new version. this PR holds a ton of additional commits not related to the PR

2024-02-14 21:48 UTC, Benoitone commented
> please wait until Frix has released a new version. this PR holds a ton of additional commits not related to the PR

It's based on develop branch.

2024-02-20 15:06 UTC, Frix-x requested changes

2024-02-20 15:06 UTC, Frix-x commented on user_templates/mcu_defaults/main/BTT_Kraken_v1.0.cfg
> +#--------------------------------------#
```suggestion
#--------------------------------------#
##### BTT Kraken MCU definition ########
#--------------------------------------#
```

2024-02-20 15:08 UTC, Frix-x commented
Just a slight change needed, but beside that I'm ready to merge

2024-02-20 16:29 UTC, Frix-x approved these changes

2024-02-20 16:29 UTC, merged