optional setting for adaptive primeline
Frix-x/klippain pull request #522
Opened 2024-03-02 18:14 UTC by Surion79

By request:
Added optional variable to enable/disable adaptive primeline. 
Priority:
1. given parameter value
2. variables value (default 1 = enabled)
3. default value (default 1 = enabled)
usage does not change, just a optional variable to setting it by printer has been introduced with this

2024-03-04 09:25 UTC, Frix-x requested changes

2024-03-04 09:25 UTC, Frix-x commented on user_templates/variables.cfg
> +variable_use_adaptive_primeline: 1 # using the adaptive primeline manages start point and direction automatically
I would change the name to "variable_prime_line_adaptive_mode" to be more aligned with the other variables and would also use True/False to stay aligned with all the other variables.cfg booleans

2024-04-11 08:21 UTC, Surion79 commented
Waiting for review

2024-05-02 18:44 UTC, arcadien commented
👍

2024-06-18 08:58 UTC, Frix-x approved these changes

2024-06-18 08:59 UTC, merged