added variable for timeout handling
Frix-x/klippain pull request #525
Opened 2024-03-03 15:34 UTC by Surion79

added variable to prevent calling M84 on timeout.
With the G2Z beta, gantry sag is a potenial issue, especially if toolhead is located near the edges.
with the introduced variable, it is now possible to prevent M84 on timeout.

it was copied based on the already existing end print variables, except that i did not added the heater off due to functional safety concerns.

2024-03-04 08:48 UTC, Frix-x commented
Wouldn't this be a safety issue since a timeout means everything should usually stop to prevent a problem?
Keeping the motors under power seems a bit counterproductive and would add a security flaw IMHO...

2024-06-18 09:01 UTC, Frix-x requested changes
Thanks, just a small change about the default value to be able to merge :)

2024-06-18 09:01 UTC, Frix-x commented on user_templates/variables.cfg
> +variable_disable_motors_on_timeout: False
Can you update the default to `True` here? The goal is to align it with the `default(1)` from the macro

2026-05-13 23:47 UTC, mjonuschat commented
I’m going to close this PR for now because feedback hasn't been addressed in a long time.

2026-05-13 23:47 UTC, closed without merging