Add 5160 based sensorless configs
Frix-x/klippain pull request #532
Opened 2024-03-04 19:51 UTC by EricZimmerman

Add 2160 and 5160 sensorless

2024-03-04 20:09 UTC, EricZimmerman commented
Added files based on work with Kraken to get it up and running. Klippy log attached as well for verification

[KrakenKlippy.log](https://github.com/Frix-x/klippain/files/14486664/KrakenKlippy.log)

2024-03-04 22:37 UTC, Surion79 commented
I would really reconsider the integration part. especially that the sense resistor option is very specific to Kraken, I don't think it is a good idea to put all in the same pot. Also removing the spi_speed on TMC2240 is not really topic in this PR?
in the config, we have for the early V0 release a "V0specific.cfg" on the Z axis i believe. So i think it would be an idea to consider to name it "KrakenSpecific" or something.
But well, something for @Frix-x to decide

2024-03-04 22:37 UTC, Surion79 commented
and please, base branch to develop :)

2024-03-04 22:38 UTC, EricZimmerman commented
Spi speed was doubled up in the file I removed it from.

2024-04-04 12:35 UTC, EricZimmerman commented
Ping and tease against develop

2024-04-18 16:02 UTC, Surion79 commented
well, i am not 100% happy with setting default rsense for Kraken on the tmc2160. but on the other hand, no one else has tmc2160 (yet)

2024-04-18 16:22 UTC, EricZimmerman commented
i am just going by the kraken docs. its all i could find

2024-06-19 08:57 UTC, Frix-x requested changes
I htink there is a small mistake in this PR, can you have a check please?

2024-06-19 08:57 UTC, Frix-x commented on config/software/sensorless_homing/sensorless_TMC2160_5160.cfg
> +driver_SGT: -64
I think here it's "tmc5160"

2024-06-19 08:57 UTC, Frix-x commented on config/software/sensorless_homing/sensorless_TMC2160_5160.cfg
> +driver_SGT: -64  # -64 is most sensitive value, 63 is least sensitive
Same here: I think it's "tmc5160"

2024-07-14 18:25 UTC, ksummers92 commented on config/software/sensorless_homing/sensorless_TMC2160_5160.cfg
> +endstop_pin: tmc5160_stepper_x:virtual_endstop
tmc5160_stepper_x should be tmc5160_stepper_y.

2024-11-21 21:07 UTC, akashrpatel commented on config/hardware/axis/Y/TMC/TMC2160.cfg
> +variable_x_driver: "tmc5160"
should be: variable_y_driver

2026-05-13 23:13 UTC, mjonuschat commented
Resolved by commit 892d8a2

2026-05-13 23:13 UTC, closed without merging