Cartographer probe config
Frix-x/klippain pull request #581
Opened 2024-04-18 14:22 UTC by xyleth

This is an attempt to add the Cartographer eddy sensor probe to Klippain in the same style as the Beacon probe.

This config is tested and works on my Voron 2.4r2 300mm.

2024-04-18 14:50 UTC, Surion79 requested changes
for completeness, please add the the cartographer.conf for moonraker update manager to the moonraker folder and the include line in the moonraker.conf file. thanks :) Otherwise it is good

2024-04-18 14:50 UTC, Surion79 commented on user_templates/printer.cfg
> +## Cartographer probe also used as virtual Z endstop. Do not forget to install the plugin and add the [cartographer] section to make it work!
i would precise it here (i know it is not done in beacon), and write to add a cartographer section to the overrides.

2024-04-18 16:11 UTC, Surion79 commented
please add a macro file with the probe_calibrate as it is stated here:
https://docs.cartographer3d.com/cartographer-probe/installation-and-setup/v2-and-v3-probes-w-input-shaping/cartographer-with-input-shaping-v2-and-v3-hybrid
![image](https://github.com/Frix-x/klippain/assets/102791900/db2d185f-9af6-43c7-b44e-094c349d73b2)

2024-04-18 17:46 UTC, xyleth commented
Added as requested in latest commit.

2024-06-04 21:37 UTC, nbaer89 commented
Just want to add, I implemented this into my install and I get an error due to the [safe_z_home] section. I had to remove it to get it to work, but that leaves me having to be careful about where my probe is when z-homing as it can occur off the bed and cause serious problems.

2024-06-14 10:16 UTC, Tecnologic commented
Hi, any progress here? I have a Cartographer in my Micron+ and would like to give this a try. What do u suggest is the best way? Just checkout the pull request?

2024-06-21 16:16 UTC, Surion79 commented
@xyleth could you please update your branch so we can attempt a merge?
Thanks

2024-07-03 10:11 UTC, Tecnologic commented
hi xyleth, i tryed ur changes with my config but have a conflict with sensorless homing cause u define safe home z with ur configs. "homing_override and safe_z_homing cannot be used simultaneously". so if i remove the safe_home z, there is another error "Unknown pin chip name 'cartographer'" according to carto trouble shooting its releated to the order of definition and usage of the carto in the config. i assume its the lis2dw pin because its gone when i remove the include for the carto lis2dw. After that u face the error Unknown pin chip name 'probe' error which is again releated to config order of definition and usage. 

I'm willing to help with this but unsure how i can help. i dont think that another pull request with my changes is the appropriate way to have this working.

2024-07-03 10:29 UTC, xyleth commented
Hi!

Hmm, I recently changed to sensorless homing and it works fine, but to be honest I've forgotten what it was I had to change to make it work!  My printer has been out of action due to extruder issues so I haven't looked at it for a while.

realistically it is going to be next week sometime before I can sit down and focus on getting this sorted, work and other commitments have tied up all my time between now and then.  I can see that the PR needs to be updated to be against the most recent release of the Klippain code and then re-submitted.

2024-07-03 10:55 UTC, Tecnologic commented
I just manually added the line of the pull so maybe I made a mistake there.  Should have time in evening to just switch to Ur branch and test locally on my machine. 

My time is limited to so don't mind. But 2 persons with limited time is more than one:)

2026-06-13 15:46 UTC, mjonuschat commented
Implemented in the Z probe framework, confirmed working after 6ea2917db10957f2068b6ac7b7b133ef2c05d36d.

Closing this out as duplicate.

2026-06-13 15:46 UTC, closed without merging