feature(tap) Added chaoticlab CNC tap settings.
Frix-x/klippain pull request #632
Opened 2024-07-30 18:41 UTC by jackmoxley

Adding the choatic lab cnc probe, which has a higher threshold as it is more prone to failure on gantry checking and height maps.

It used the base voron_tap, so all the macros and pin settings remain.

2024-07-30 19:35 UTC, EricZimmerman commented
Why is this needed vs just straight up overriding the [probe] block?

2024-07-30 19:37 UTC, jackmoxley commented
> Why is this needed vs just straight up overriding the [probe] block?

I did exactly that, but in the nature of providing out the box support for everyone that uses these mods, I thought it would be helpful.

You could say the same thing about anny klippain config file.

2025-01-08 12:06 UTC, Frix-x requested changes
Hey, thanks for the PR!

I'm all for it. It's part of the work I wanted to do to make more probes easily available without having to put the offsets in the overrides every time. So this might be a good candidate for a first file like this.

Eric, the goal would be to be able to select with Klicky, Euclid, etc... instead of "dockable", since not all dockable probes are similar. But they will all reference this dockable probe file under the hood with the added customizations.

However, @jackmoxley can you add the entry in the printer.cfg file to be able to select it? Thanks!

2026-05-13 23:38 UTC, mjonuschat commented
I’m going to close this PR for now because the feedback hasn't been addressed for a long time.

2026-05-13 23:38 UTC, closed without merging