Support beacon_klipper version >= 2.0.0, a.k.a Beacon Contact
Frix-x/klippain pull request #637
Opened 2024-08-09 05:39 UTC by crkochan

My initial take on fixing #636.

 Beacon Contact introduced [code in their BeaconHomingHelper class](https://github.com/beacon3d/beacon_klipper/blob/730836d40f1bf02b6f1bf08649dcaacca9aee900/beacon.py#L2371-L2375) that specifically balks when `[homing_override]` is present in the Klipper config.
 
My attempt at working around this was to...

- Create a separate `beacon_contact.cfg` in the hardware probes folder
- Specify `beacon_contact` as `variable_probe_type_enabled` to be used by future g-code conditionals
- Update `machine.cfg` so that `homing_override.cfg` is not always included
- Move the `homing_override.cfg` include into `generic_probe.cfg` base macro so that every other probe can still get it

There are still a couple more changes I want to make based on the Beacon documentation that are centered on the start_print macro, but I'm opening this as a draft PR so that I can also include any feedback, since this is my first contribution.

2024-08-25 12:06 UTC, ksummers92 commented
I tried your implementation and there are some default values that are not included that causes an error "Option 'home_method' is not valid in section 'beacon'". This is likely due to home_xy_position not being defined by some kind of defaults. Probably best to retrieve the zero reference position/bed center like the homing_override.cfg does and assume that as the home_xy_position.

2024-08-26 02:41 UTC, crkochan commented
I started working on this PR after I already had Beacon more or less up and running, so you're right, I already had `home_xy_position` defined in my overrides.cfg file.

Unfortunately, the value needs to be defined outside of a gcode macro, so I can't use the same trick that `homing_override.cfg` does.

I'm not quite sure what the optimal solution is. I can add [the documented recommended defaults](https://docs.beacon3d.com/contact/#52-configuration) into `beacon_contact.cfg`, and pick a set of coordinates that are not totally outlandish for a Voron Trident or V2, but that might not fly for users of other printers.

Maybe that, plus adding a commented beacon block to the user_templates overrides.cfg, basically some way of signaling that for contact, a user is probably going to want to have some sort of config override setup.

Just to share, this is my beacon block present in `overrides.cfg`.

```
[beacon]
serial: /dev/serial/by-id/usb-Beacon_Beacon_RevH_9AA5D66B5154354D38202020FF0A0B36-if00
x_offset: 0
y_offset: 26.5
mesh_main_direction: x
mesh_runs: 2
accel_axes_map: x, y, z
home_xy_position: 150, 150
home_z_hop: 5
home_z_hop_speed: 30
home_xy_move_speed: 300
autocal_speed: 5
home_method: proximity
home_method_when_homed: proximity
home_autocalibrate: never
```

2024-09-27 20:36 UTC, zanmoskotevc commented
Hey @crkochan, any update on this? I'd love to see support for this added.

2024-09-30 23:01 UTC, crkochan commented
None from my side. I've been running a series of post-kit-build prints for some new parts and future upgrades using my fork branch, and the pieces have been turning out just fine on my V2.4.

It may not be up to snuff in terms of being merged into mainline because of the need for users to add Contact-specific settings that are perhaps unique to their machine, or class of printer, into their overrides file in order to avoid the potential for cryptic and/or misleading error messages on Klipper start that would come from the Beacon module.

I'm happy to implement any feedback from the maintainers.

2024-11-16 21:38 UTC, KazachThi commented
Hey, @crkochan I have been using your setup to run beacon contact with no problems. All is working as intended. 
One thing (and i might be wrong on this one), we have one unnecessary beacon contact calibration.
Order in my case :
 - Homing
 - pre-heating hotend
 - bed heating
 - chamber heating
 - Beacon contact calibration (first)
 - GQL
 - Beacon contact calibration (second)
 - Beacon contact calibration (third)
 - Bed mesh
 - Beacon contact calibration (fourth)
 - Heating hotend
 - Nozzle clean
 - Prime line
 - Printing

So, second and third are redundant ?
Hope this helps.

2024-11-17 06:00 UTC, crkochan commented
> So, second and third are redundant ? Hope this helps.

Yes. Per the Beacon docs, QGL/z tilt adjust and bed mesh should be book-ended by calibrations. 

I'm not sure where the extra calibrations are coming from in your case.

2024-12-02 16:05 UTC, laukejas commented
Has there been any progress with this?

2025-01-06 13:49 UTC, Frix-x commented
Hello, thanks for the PR. I'm back on the subject and bought a beacon to test it. I'll merge it as soon as I get it installed :)

2025-01-08 09:45 UTC, Frix-x requested changes
So I've made a review of the code (I haven't tested it yet as I'm still waiting for my beacon to arrive), but I already have some changes requested to simplify the code a bit.

I really want to keep it simple for Klippain users to use it and avoid duplicating macros, etc...

2025-01-08 09:45 UTC, Frix-x commented on config/hardware/probes/beacon_contact.cfg
> +    _beacon_contact_hardware_check
Is it possible to move this check in the startup.cfg file? There's already a few things that are checked at Klippain startup and this could be added in the _INIT_CHECKPROBECONF macro that is done exactly for this purpose.

https://github.com/Frix-x/klippain/blob/main/macros/miscs/startup.cfg

2025-01-08 09:45 UTC, Frix-x commented on macros/base/probing/beacon_probe.cfg
> +    SET_GCODE_VARIABLE MACRO=ACTIVATE_PROBE VARIABLE=is_active VALUE=False
I think this duplication of ACTIVATE/DEACTIVATE_PROBE doesn't make sense and could be avoided. In fact, these original macros were designed to be generic and accept any type of probe.

If I understand correctly, you made this duplication choice because you added `[include ../homing/homing_override.cfg]` to the generic_probe.cfg file. But maybe you can move that line to any probe type that needs the default homing_override sequence, and keep the generic_probe.cfg really generic to accept that content for beacon as well.

See my next comments.

2025-01-08 09:45 UTC, Frix-x commented on macros/base/probing/generic_probe.cfg
> +[include ../homing/homing_override.cfg]
Move this line into each probe type that require it.

2025-01-08 09:45 UTC, Frix-x commented on macros/base/probing/generic_probe.cfg
>  [gcode_macro ACTIVATE_PROBE]
And add the beacon specificity in these macros.

2025-01-08 09:45 UTC, Frix-x commented on macros/base/probing/overrides/beacon_probe_overrides.cfg
> +[gcode_macro FAST_QUAD_GANTRY_LEVEL]
I'm not a fan of using a new `FAST_...` macro for a duplication of the same feature that QGL already provide but adapted to be faster. I'm pretty sure everyone will always want to use the fast version.

So why not merging this in the original overrides files with a check on the `beacon_contact` (and also standard `beacon`?) probe type to do the fast version?
`https://github.com/Frix-x/klippain/blob/main/macros/base/probing/overrides/qgl.cfg`
`https://github.com/Frix-x/klippain/blob/main/macros/base/probing/overrides/z_tilt.cfg`

This way, when running the standard QGL/Z_TILT macro that is already available in the frontends, it will always work for everyone, using the fast way if you can go fast with a beacon.

2025-01-08 09:45 UTC, Frix-x commented on macros/base/probing/overrides/beacon_probe_overrides.cfg
> +[gcode_macro FAST_Z_TILT_ADJUST]
Same comment here about the `FAST_...` version of the Z_TILT_ADJUST macro

2025-02-24 16:39 UTC, tavalin commented
Hi, is there any progress on this on plans to progress this?  The Beacon contact functionality has been out for more than 6 months now so it's a shame that Klippain doesn't yet officially support it

2025-04-15 09:58 UTC, sima-it commented
So I assume, this will not be intregrated then. Is the Poject dead?

2025-04-15 10:25 UTC, gueee commented
> So I assume, this will not be intregrated then. Is the Poject dead?

it seems to be dead at that point.
nevertheless, I forked the repo and will extend the project, but I can't say when I'm ready to publish it.

for now I pulled my own repo, so it's not marked dirty and beacon contact and AWD are working for me.

2025-04-15 12:33 UTC, sima-it commented
thx mate, 
i'm running also the changes from [crkochan] with no problems so far just the dirty repo keeps bothering me ;)

2025-04-15 13:13 UTC, gueee commented
I already extended klippain a bit, especially regarding bed sizes with a dedicated configuration option to choose any bed size, which calculates the offsets for bed mesh and the configuration option for multiple motors on x and y, including tmc driver settings for the additional steppers.

I'm also trying to create a web based gui for automatically generating the configs, or rather the overrides. 

if you're a little patient I'm gonna publish it, probably under a new name, since there are too many changes that somehow left the path of klippain...

2025-04-15 18:02 UTC, sima-it commented
looking forward to test it out, thanks for your effort

2025-04-20 18:32 UTC, roykrikke commented
@Frix-x Can you give klippain users an indication of when this feature will be integrated? It would be great to get some feedback from you.

2025-12-06 23:56 UTC, ormarek commented
Any news on that? It's been over a year
@crkochan @gueee @Frix-x

2025-12-10 06:49 UTC, gueee commented
> Any news on that? It's been over a year
> @crkochan @gueee @Frix-x

I guess Frix-x hasn't time to maintain the project anymore, but I started a similar project, maybe you wanna have a look at it?!

https://github.com/gueee/gschpoozi

a warning, it's in alpha state, but I guess I can get it to a stable beta today!

it's mostly functional already though.

2025-12-12 09:14 UTC, ormarek commented
@gueee hey, that looks super promising! Unfortunately I have only one printer and currently no budget for fixes and time to play with stuff so I might have to wait a little until I have some spare cash for a printer before trying that out (reason is alpha/beta).

But I started your repository! Interactive setup sounds like very neat way to set up things

2026-04-23 03:51 UTC, mjonuschat commented
Closed by #721

2026-04-23 03:51 UTC, closed without merging