Make filament retract user configurable in base macros
Frix-x/klippain pull request #642
Opened 2024-08-27 01:24 UTC by tehniemer

Add user configurable variable for filament retract in end and cancel print macros.

2024-10-01 11:39 UTC, tehniemer commented
I think this is still a valid addition.

2025-01-06 13:43 UTC, Frix-x commented
Thanks for the PR!

I want to merge this. But as stated in #658 this need to be linked to the loading during a purge at the beginning of a print. Indeed, what you retract at the end of a print should be inserted again at the beginning of the next one (at least it was designed like that).

Can you please complete the PR with this additional need?

2025-01-06 15:00 UTC, wight554 commented
In my testing I noticed that it's better to push a little bit more than retracted, like 10-20% more 
I retract 30 and push 35, otherwise half of my purge line is somewhat empty. However would be better if anyone else shares their experience

2025-01-06 15:03 UTC, tehniemer commented
I just added an unretract to the prime line macro equal to the retract in the cancel and end print macros. Please let me know if that's good enough or if you would like an additional user variable for the extra push as mentioned by @wight554

2025-01-06 15:33 UTC, Frix-x commented
Yes, that's right, I think having a percentage factor combined to this could be a good idea.
Like by default 15% more: it doesn't cost much to do this and should be pretty harmless.

2025-01-07 01:14 UTC, tehniemer commented
OK, I've added #641 and #645 into this one and created a second variable for the nozzle prime.

2025-01-07 17:07 UTC, Frix-x requested changes
I think we are near a merge. Just a few changes on my side, but nothing very problematic :)

2025-01-07 17:07 UTC, Frix-x commented on macros/helpers/nozzle_cleaning.cfg
> +        G1 E-({RETRACT}-1.7) F150
Can you replace it by like 10% like on the following suggestion? It should be pretty equivalent but also more compatible with any value of RETRACT.

```suggestion
        G1 E-({RETRACT}-{RETRACT*0.1}) F150
```

2025-01-07 17:07 UTC, Frix-x commented on user_templates/variables.cfg
> +variable_unretract_length: 23
Maybe for it to be more clear and show that both variables are linked, it could be made like this.

```suggestion
## Length of filament to retract/retract to disengage it from the heatbreak.
## This is to reduce final print oozing, but also to prevent heatcreep, clogging, and allow cold filament change between prints.
variable_retract_length: 20
variable_unretract_length: 23
```

2025-01-07 18:40 UTC, tehniemer commented
I'm good with both of those.

2025-01-08 08:45 UTC, Frix-x approved these changes

2025-01-08 08:46 UTC, Frix-x commented
Ok I'm good with it now and will merge! Thank you :)

2025-01-08 08:55 UTC, merged